/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUserPermitInput
 */
export interface PostUserPermitInput {
    /**
     * 
     * @type {string}
     * @memberof PostUserPermitInput
     */
    groupId: string;
    /**
     * 
     * @type {string}
     * @memberof PostUserPermitInput
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PostUserPermitInput
     */
    policyId: string;
}

export function PostUserPermitInputFromJSON(json: any): PostUserPermitInput {
    return PostUserPermitInputFromJSONTyped(json, false);
}

export function PostUserPermitInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUserPermitInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'userId': json['userId'],
        'policyId': json['policyId'],
    };
}

export function PostUserPermitInputToJSON(value?: PostUserPermitInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'groupId': value.groupId,
        'userId': value.userId,
        'policyId': value.policyId,
    };
}


