/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subgroup
 */
export interface Subgroup {
    /**
     * 
     * @type {string}
     * @memberof Subgroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Subgroup
     */
    name: string;
}

export function SubgroupFromJSON(json: any): Subgroup {
    return SubgroupFromJSONTyped(json, false);
}

export function SubgroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subgroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SubgroupToJSON(value?: Subgroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


