/* tslint:disable */
/* eslint-disable */
/**
 * Nexxiot Boards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Location,
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
} from './';

/**
 * 
 * @export
 * @interface NexxiotAssetMeasurementUpdatedAt
 */
export interface NexxiotAssetMeasurementUpdatedAt {
    /**
     * 
     * @type {Location}
     * @memberof NexxiotAssetMeasurementUpdatedAt
     */
    location: Location;
    /**
     * 
     * @type {Date}
     * @memberof NexxiotAssetMeasurementUpdatedAt
     */
    updatedAt: Date;
}

export function NexxiotAssetMeasurementUpdatedAtFromJSON(json: any): NexxiotAssetMeasurementUpdatedAt {
    return NexxiotAssetMeasurementUpdatedAtFromJSONTyped(json, false);
}

export function NexxiotAssetMeasurementUpdatedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): NexxiotAssetMeasurementUpdatedAt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'location': LocationFromJSON(json['location']),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function NexxiotAssetMeasurementUpdatedAtToJSON(value?: NexxiotAssetMeasurementUpdatedAt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'location': LocationToJSON(value.location),
        'updatedAt': (value.updatedAt.toISOString().substr(0,10)),
    };
}


