/* tslint:disable */
/* eslint-disable */
/**
 * Nexxiot Boards
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InternalTemperature,
    InternalTemperatureFromJSON,
    InternalTemperatureFromJSONTyped,
    InternalTemperatureToJSON,
} from './';

/**
 * 
 * @export
 * @interface NexxiotDeviceMeasurementUpdatedAt
 */
export interface NexxiotDeviceMeasurementUpdatedAt {
    /**
     * 
     * @type {InternalTemperature}
     * @memberof NexxiotDeviceMeasurementUpdatedAt
     */
    internalTemperature: InternalTemperature;
    /**
     * 
     * @type {Date}
     * @memberof NexxiotDeviceMeasurementUpdatedAt
     */
    updatedAt: Date;
}

export function NexxiotDeviceMeasurementUpdatedAtFromJSON(json: any): NexxiotDeviceMeasurementUpdatedAt {
    return NexxiotDeviceMeasurementUpdatedAtFromJSONTyped(json, false);
}

export function NexxiotDeviceMeasurementUpdatedAtFromJSONTyped(json: any, ignoreDiscriminator: boolean): NexxiotDeviceMeasurementUpdatedAt {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'internalTemperature': InternalTemperatureFromJSON(json['internalTemperature']),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function NexxiotDeviceMeasurementUpdatedAtToJSON(value?: NexxiotDeviceMeasurementUpdatedAt | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'internalTemperature': InternalTemperatureToJSON(value.internalTemperature),
        'updatedAt': (value.updatedAt.toISOString().substr(0,10)),
    };
}


