/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AelerBoard
 */
export interface AelerBoard {
    /**
     * 
     * @type {string}
     * @memberof AelerBoard
     */
    boardId: string;
    /**
     * Board build date
     * @type {Date}
     * @memberof AelerBoard
     */
    buildDate?: Date;
    /**
     * Board hardware version
     * @type {string}
     * @memberof AelerBoard
     */
    hwVersion?: string;
    /**
     * Board firmware version
     * @type {string}
     * @memberof AelerBoard
     */
    fwVersion?: string;
    /**
     * Board hardware minor revision
     * @type {string}
     * @memberof AelerBoard
     */
    hwMinorRevision?: string;
    /**
     * Board firmware minor revision
     * @type {string}
     * @memberof AelerBoard
     */
    fwMinorRevision?: string;
    /**
     * hasGps
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasGps?: boolean;
    /**
     * hasShock
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasShock?: boolean;
    /**
     * hasTempExt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasTempExt?: boolean;
    /**
     * hasTempInt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasTempInt?: boolean;
    /**
     * hasPressureExt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasPressureExt?: boolean;
    /**
     * hasPressureInt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasPressureInt?: boolean;
    /**
     * hasGases
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasGases?: boolean;
    /**
     * hasLightInt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasLightInt?: boolean;
    /**
     * hasLightExt
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasLightExt?: boolean;
    /**
     * hasDoor
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasDoor?: boolean;
    /**
     * hasRFID
     * @type {boolean}
     * @memberof AelerBoard
     */
    hasRFID?: boolean;
}

export function AelerBoardFromJSON(json: any): AelerBoard {
    return AelerBoardFromJSONTyped(json, false);
}

export function AelerBoardFromJSONTyped(json: any, ignoreDiscriminator: boolean): AelerBoard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boardId': json['boardId'],
        'buildDate': !exists(json, 'buildDate') ? undefined : (new Date(json['buildDate'])),
        'hwVersion': !exists(json, 'hwVersion') ? undefined : json['hwVersion'],
        'fwVersion': !exists(json, 'fwVersion') ? undefined : json['fwVersion'],
        'hwMinorRevision': !exists(json, 'hwMinorRevision') ? undefined : json['hwMinorRevision'],
        'fwMinorRevision': !exists(json, 'fwMinorRevision') ? undefined : json['fwMinorRevision'],
        'hasGps': !exists(json, 'hasGps') ? undefined : json['hasGps'],
        'hasShock': !exists(json, 'hasShock') ? undefined : json['hasShock'],
        'hasTempExt': !exists(json, 'hasTempExt') ? undefined : json['hasTempExt'],
        'hasTempInt': !exists(json, 'hasTempInt') ? undefined : json['hasTempInt'],
        'hasPressureExt': !exists(json, 'hasPressureExt') ? undefined : json['hasPressureExt'],
        'hasPressureInt': !exists(json, 'hasPressureInt') ? undefined : json['hasPressureInt'],
        'hasGases': !exists(json, 'hasGases') ? undefined : json['hasGases'],
        'hasLightInt': !exists(json, 'hasLightInt') ? undefined : json['hasLightInt'],
        'hasLightExt': !exists(json, 'hasLightExt') ? undefined : json['hasLightExt'],
        'hasDoor': !exists(json, 'hasDoor') ? undefined : json['hasDoor'],
        'hasRFID': !exists(json, 'hasRFID') ? undefined : json['hasRFID'],
    };
}

export function AelerBoardToJSON(value?: AelerBoard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boardId': value.boardId,
        'buildDate': value.buildDate === undefined ? undefined : (value.buildDate.toISOString().substr(0,10)),
        'hwVersion': value.hwVersion,
        'fwVersion': value.fwVersion,
        'hwMinorRevision': value.hwMinorRevision,
        'fwMinorRevision': value.fwMinorRevision,
        'hasGps': value.hasGps,
        'hasShock': value.hasShock,
        'hasTempExt': value.hasTempExt,
        'hasTempInt': value.hasTempInt,
        'hasPressureExt': value.hasPressureExt,
        'hasPressureInt': value.hasPressureInt,
        'hasGases': value.hasGases,
        'hasLightInt': value.hasLightInt,
        'hasLightExt': value.hasLightExt,
        'hasDoor': value.hasDoor,
        'hasRFID': value.hasRFID,
    };
}


