/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoorEvent,
    DoorEventFromJSON,
    DoorEventFromJSONTyped,
    DoorEventToJSON,
    LightEvent,
    LightEventFromJSON,
    LightEventFromJSONTyped,
    LightEventToJSON,
    ShockEvent,
    ShockEventFromJSON,
    ShockEventFromJSONTyped,
    ShockEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface Events
 */
export interface Events {
    /**
     * 
     * @type {ShockEvent}
     * @memberof Events
     */
    shockEvent?: ShockEvent;
    /**
     * 
     * @type {LightEvent}
     * @memberof Events
     */
    lightEvent?: LightEvent;
    /**
     * 
     * @type {DoorEvent}
     * @memberof Events
     */
    doorEvent?: DoorEvent;
}

export function EventsFromJSON(json: any): Events {
    return EventsFromJSONTyped(json, false);
}

export function EventsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Events {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shockEvent': !exists(json, 'shockEvent') ? undefined : ShockEventFromJSON(json['shockEvent']),
        'lightEvent': !exists(json, 'lightEvent') ? undefined : LightEventFromJSON(json['lightEvent']),
        'doorEvent': !exists(json, 'doorEvent') ? undefined : DoorEventFromJSON(json['doorEvent']),
    };
}

export function EventsToJSON(value?: Events | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shockEvent': ShockEventToJSON(value.shockEvent),
        'lightEvent': LightEventToJSON(value.lightEvent),
        'doorEvent': DoorEventToJSON(value.doorEvent),
    };
}


