/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DoorEvent,
    DoorEventFromJSON,
    DoorEventFromJSONTyped,
    DoorEventToJSON,
    LightEvent,
    LightEventFromJSON,
    LightEventFromJSONTyped,
    LightEventToJSON,
    LteServiceEvent,
    LteServiceEventFromJSON,
    LteServiceEventFromJSONTyped,
    LteServiceEventToJSON,
    ShockEvent,
    ShockEventFromJSON,
    ShockEventFromJSONTyped,
    ShockEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface EventValues
 */
export interface EventValues {
    /**
     * 
     * @type {ShockEvent}
     * @memberof EventValues
     */
    shockEvent?: ShockEvent;
    /**
     * 
     * @type {LightEvent}
     * @memberof EventValues
     */
    lightEvent?: LightEvent;
    /**
     * 
     * @type {DoorEvent}
     * @memberof EventValues
     */
    doorEvent?: DoorEvent;
    /**
     * 
     * @type {LteServiceEvent}
     * @memberof EventValues
     */
    lteServiceEvent?: LteServiceEvent;
    /**
     * the subtype of the event in question: e.g. accelEvntAVecm for accelerometer events
     * @type {string}
     * @memberof EventValues
     */
    eventSubTypeName?: string;
}

export function EventValuesFromJSON(json: any): EventValues {
    return EventValuesFromJSONTyped(json, false);
}

export function EventValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shockEvent': !exists(json, 'shockEvent') ? undefined : ShockEventFromJSON(json['shockEvent']),
        'lightEvent': !exists(json, 'lightEvent') ? undefined : LightEventFromJSON(json['lightEvent']),
        'doorEvent': !exists(json, 'doorEvent') ? undefined : DoorEventFromJSON(json['doorEvent']),
        'lteServiceEvent': !exists(json, 'lteServiceEvent') ? undefined : LteServiceEventFromJSON(json['lteServiceEvent']),
        'eventSubTypeName': !exists(json, 'eventSubTypeName') ? undefined : json['eventSubTypeName'],
    };
}

export function EventValuesToJSON(value?: EventValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shockEvent': ShockEventToJSON(value.shockEvent),
        'lightEvent': LightEventToJSON(value.lightEvent),
        'doorEvent': DoorEventToJSON(value.doorEvent),
        'lteServiceEvent': LteServiceEventToJSON(value.lteServiceEvent),
        'eventSubTypeName': value.eventSubTypeName,
    };
}


