/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LatestMessageDate
 */
export interface LatestMessageDate {
    /**
     * date at which the message was RECORDED
     * @type {Date}
     * @memberof LatestMessageDate
     */
    messageDate: Date;
    /**
     * type of message
     * @type {string}
     * @memberof LatestMessageDate
     */
    messageType: string;
    /**
     * 
     * @type {Date}
     * @memberof LatestMessageDate
     */
    updatedAt: Date;
}

export function LatestMessageDateFromJSON(json: any): LatestMessageDate {
    return LatestMessageDateFromJSONTyped(json, false);
}

export function LatestMessageDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): LatestMessageDate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'messageDate': (new Date(json['messageDate'])),
        'messageType': json['messageType'],
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function LatestMessageDateToJSON(value?: LatestMessageDate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'messageDate': (value.messageDate.toISOString()),
        'messageType': value.messageType,
        'updatedAt': (value.updatedAt.toISOString()),
    };
}


