/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LightEvent
 */
export interface LightEvent {
    /**
     * 
     * @type {number}
     * @memberof LightEvent
     */
    devId?: number;
    /**
     * 
     * @type {number}
     * @memberof LightEvent
     */
    status?: number;
    /**
     * 
     * @type {number}
     * @memberof LightEvent
     */
    centiLuxExternal?: number;
    /**
     * 
     * @type {number}
     * @memberof LightEvent
     */
    eventType?: number;
}

export function LightEventFromJSON(json: any): LightEvent {
    return LightEventFromJSONTyped(json, false);
}

export function LightEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): LightEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'devId': !exists(json, 'devId') ? undefined : json['devId'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'centiLuxExternal': !exists(json, 'centiLuxExternal') ? undefined : json['centiLuxExternal'],
        'eventType': !exists(json, 'eventType') ? undefined : json['eventType'],
    };
}

export function LightEventToJSON(value?: LightEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'devId': value.devId,
        'status': value.status,
        'centiLuxExternal': value.centiLuxExternal,
        'eventType': value.eventType,
    };
}


