/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PowerBudgetValues
 */
export interface PowerBudgetValues {
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    tSleepSeconds?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    nWakeForCom?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    targetAutonomy?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    powerCtrlMode?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    batterySoCfromVoC?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    batterySoCfromCoulomb?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    batterySoH?: number;
    /**
     * 
     * @type {number}
     * @memberof PowerBudgetValues
     */
    projectedAutonomy?: number;
}

export function PowerBudgetValuesFromJSON(json: any): PowerBudgetValues {
    return PowerBudgetValuesFromJSONTyped(json, false);
}

export function PowerBudgetValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PowerBudgetValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tSleepSeconds': !exists(json, 'tSleepSeconds') ? undefined : json['tSleepSeconds'],
        'nWakeForCom': !exists(json, 'nWakeForCom') ? undefined : json['nWakeForCom'],
        'targetAutonomy': !exists(json, 'targetAutonomy') ? undefined : json['targetAutonomy'],
        'powerCtrlMode': !exists(json, 'powerCtrlMode') ? undefined : json['powerCtrlMode'],
        'batterySoCfromVoC': !exists(json, 'batterySoCfromVoC') ? undefined : json['batterySoCfromVoC'],
        'batterySoCfromCoulomb': !exists(json, 'batterySoCfromCoulomb') ? undefined : json['batterySoCfromCoulomb'],
        'batterySoH': !exists(json, 'batterySoH') ? undefined : json['batterySoH'],
        'projectedAutonomy': !exists(json, 'projectedAutonomy') ? undefined : json['projectedAutonomy'],
    };
}

export function PowerBudgetValuesToJSON(value?: PowerBudgetValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tSleepSeconds': value.tSleepSeconds,
        'nWakeForCom': value.nWakeForCom,
        'targetAutonomy': value.targetAutonomy,
        'powerCtrlMode': value.powerCtrlMode,
        'batterySoCfromVoC': value.batterySoCfromVoC,
        'batterySoCfromCoulomb': value.batterySoCfromCoulomb,
        'batterySoH': value.batterySoH,
        'projectedAutonomy': value.projectedAutonomy,
    };
}


