/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValuesForSensorData
 */
export interface ValuesForSensorData {
    /**
     * temperature inside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    temperature?: number;
    /**
     * temperature outside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    externalTemperature?: number;
    /**
     * humidity inside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    humidity?: number;
    /**
     * humidity outside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    externalHumidity?: number;
    /**
     * pressure inside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    pressure?: number;
    /**
     * pressure outside the container
     * @type {number}
     * @memberof ValuesForSensorData
     */
    externalPressure?: number;
    /**
     * R = right looking from outside the container - 0 is closed 1 is open
     * @type {number}
     * @memberof ValuesForSensorData
     */
    doorR?: number;
    /**
     * L = left looking from outside the container - 0 is closed 1 is open
     * @type {number}
     * @memberof ValuesForSensorData
     */
    doorL?: number;
    /**
     * Indoor air quality
     * @type {number}
     * @memberof ValuesForSensorData
     */
    iaq?: number;
    /**
     * Total Volatile Organic Compounds
     * @type {number}
     * @memberof ValuesForSensorData
     */
    ngm3TVOC?: number;
    /**
     * parts per million carbon dioxide
     * @type {number}
     * @memberof ValuesForSensorData
     */
    ppmeCO2?: number;
    /**
     * parts per million ethanol
     * @type {number}
     * @memberof ValuesForSensorData
     */
    ppbEtOH?: number;
    /**
     * outdoor air quality
     * @type {number}
     * @memberof ValuesForSensorData
     */
    oaqNO2?: number;
    /**
     * outdoor air qualiry ozone
     * @type {number}
     * @memberof ValuesForSensorData
     */
    oaqO3?: number;
    /**
     * probability of nitrogen dioxide
     * @type {number}
     * @memberof ValuesForSensorData
     */
    probNO2?: number;
    /**
     * parts per billion nitrogen dioxide
     * @type {number}
     * @memberof ValuesForSensorData
     */
    ppbNO2?: number;
    /**
     * parts per billion ozone
     * @type {number}
     * @memberof ValuesForSensorData
     */
    ppb03?: number;
    /**
     * internal light sensor
     * @type {number}
     * @memberof ValuesForSensorData
     */
    centiLux?: number;
    /**
     * external light sensor
     * @type {number}
     * @memberof ValuesForSensorData
     */
    centiLuxExternal?: number;
}

export function ValuesForSensorDataFromJSON(json: any): ValuesForSensorData {
    return ValuesForSensorDataFromJSONTyped(json, false);
}

export function ValuesForSensorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValuesForSensorData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'temperature': !exists(json, 'temperature') ? undefined : json['temperature'],
        'externalTemperature': !exists(json, 'externalTemperature') ? undefined : json['externalTemperature'],
        'humidity': !exists(json, 'humidity') ? undefined : json['humidity'],
        'externalHumidity': !exists(json, 'externalHumidity') ? undefined : json['externalHumidity'],
        'pressure': !exists(json, 'pressure') ? undefined : json['pressure'],
        'externalPressure': !exists(json, 'externalPressure') ? undefined : json['externalPressure'],
        'doorR': !exists(json, 'doorR') ? undefined : json['doorR'],
        'doorL': !exists(json, 'doorL') ? undefined : json['doorL'],
        'iaq': !exists(json, 'iaq') ? undefined : json['iaq'],
        'ngm3TVOC': !exists(json, 'ngm3TVOC') ? undefined : json['ngm3TVOC'],
        'ppmeCO2': !exists(json, 'ppmeCO2') ? undefined : json['ppmeCO2'],
        'ppbEtOH': !exists(json, 'ppbEtOH') ? undefined : json['ppbEtOH'],
        'oaqNO2': !exists(json, 'oaqNO2') ? undefined : json['oaqNO2'],
        'oaqO3': !exists(json, 'oaqO3') ? undefined : json['oaqO3'],
        'probNO2': !exists(json, 'probNO2') ? undefined : json['probNO2'],
        'ppbNO2': !exists(json, 'ppbNO2') ? undefined : json['ppbNO2'],
        'ppb03': !exists(json, 'ppb03') ? undefined : json['ppb03'],
        'centiLux': !exists(json, 'centiLux') ? undefined : json['centiLux'],
        'centiLuxExternal': !exists(json, 'centiLuxExternal') ? undefined : json['centiLuxExternal'],
    };
}

export function ValuesForSensorDataToJSON(value?: ValuesForSensorData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'temperature': value.temperature,
        'externalTemperature': value.externalTemperature,
        'humidity': value.humidity,
        'externalHumidity': value.externalHumidity,
        'pressure': value.pressure,
        'externalPressure': value.externalPressure,
        'doorR': value.doorR,
        'doorL': value.doorL,
        'iaq': value.iaq,
        'ngm3TVOC': value.ngm3TVOC,
        'ppmeCO2': value.ppmeCO2,
        'ppbEtOH': value.ppbEtOH,
        'oaqNO2': value.oaqNO2,
        'oaqO3': value.oaqO3,
        'probNO2': value.probNO2,
        'ppbNO2': value.ppbNO2,
        'ppb03': value.ppb03,
        'centiLux': value.centiLux,
        'centiLuxExternal': value.centiLuxExternal,
    };
}


