/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComputedStatuses
 */
export interface ComputedStatuses {
    /**
     * 
     * @type {string}
     * @memberof ComputedStatuses
     */
    orderStatus?: ComputedStatusesOrderStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum ComputedStatusesOrderStatusEnum {
    Created = 'CREATED',
    Accepted = 'ACCEPTED',
    AelerCanceled = 'AELER-CANCELED',
    CustomerCanceled = 'CUSTOMER-CANCELED',
    CompletedFulfilled = 'COMPLETED-FULFILLED',
    CompletedFailed = 'COMPLETED-FAILED',
    Ready = 'READY',
    Ongoing = 'ONGOING',
    Outdated = 'OUTDATED'
}

export function ComputedStatusesFromJSON(json: any): ComputedStatuses {
    return ComputedStatusesFromJSONTyped(json, false);
}

export function ComputedStatusesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComputedStatuses {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderStatus': !exists(json, 'orderStatus') ? undefined : json['orderStatus'],
    };
}

export function ComputedStatusesToJSON(value?: ComputedStatuses | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderStatus': value.orderStatus,
    };
}


