/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerBoardPairingProfileDeleteInput
 */
export interface ContainerBoardPairingProfileDeleteInput {
    /**
     * 
     * @type {string}
     * @memberof ContainerBoardPairingProfileDeleteInput
     */
    boardPairingProfileId: string;
}

export function ContainerBoardPairingProfileDeleteInputFromJSON(json: any): ContainerBoardPairingProfileDeleteInput {
    return ContainerBoardPairingProfileDeleteInputFromJSONTyped(json, false);
}

export function ContainerBoardPairingProfileDeleteInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerBoardPairingProfileDeleteInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boardPairingProfileId': json['boardPairingProfileId'],
    };
}

export function ContainerBoardPairingProfileDeleteInputToJSON(value?: ContainerBoardPairingProfileDeleteInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boardPairingProfileId': value.boardPairingProfileId,
    };
}


