/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerPatchInput
 */
export interface ContainerPatchInput {
    /**
     * container operational status
     * @type {string}
     * @memberof ContainerPatchInput
     */
    characteristics_size?: ContainerPatchInputCharacteristicsSizeEnum;
    /**
     * container type
     * @type {string}
     * @memberof ContainerPatchInput
     */
    characteristics_type?: ContainerPatchInputCharacteristicsTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    containerVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    characteristics_maxPayload?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    characteristics_builtYear?: string;
    /**
     * volumne
     * @type {number}
     * @memberof ContainerPatchInput
     */
    volume?: number;
    /**
     * weight
     * @type {number}
     * @memberof ContainerPatchInput
     */
    characteristics_tare?: number;
    /**
     * Inspection Date
     * @type {Date}
     * @memberof ContainerPatchInput
     */
    inspectionDate?: Date;
    /**
     * CSC Cert No.
     * @type {string}
     * @memberof ContainerPatchInput
     */
    cscCertNo?: string;
    /**
     * createdAt
     * @type {Date}
     * @memberof ContainerPatchInput
     */
    cscCertDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    characteristics_grade?: string;
    /**
     * cscCertLink
     * @type {string}
     * @memberof ContainerPatchInput
     */
    cscCertLink?: string;
    /**
     * end panel
     * @type {boolean}
     * @memberof ContainerPatchInput
     */
    electronicsCharging?: boolean;
    /**
     * insurance
     * @type {string}
     * @memberof ContainerPatchInput
     */
    insurance?: string;
    /**
     * Insurance date
     * @type {Date}
     * @memberof ContainerPatchInput
     */
    insuranceDate?: Date;
    /**
     * cameraExt
     * @type {boolean}
     * @memberof ContainerPatchInput
     */
    cameraExt?: boolean;
    /**
     * cameraInt
     * @type {boolean}
     * @memberof ContainerPatchInput
     */
    cameraInt?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    floorType?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    doorType?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerPatchInput
     */
    depotId?: string;
    /**
     * user id
     * @type {string}
     * @memberof ContainerPatchInput
     */
    lastChangedBy?: string;
}

/**
* @export
* @enum {string}
*/
export enum ContainerPatchInputCharacteristicsSizeEnum {
    _20ft = '20ft',
    _40ft = '40ft',
    _45ft = '45ft'
}/**
* @export
* @enum {string}
*/
export enum ContainerPatchInputCharacteristicsTypeEnum {
    Reefer = 'REEFER',
    Flexitank = 'FLEXITANK',
    Normal = 'NORMAL'
}

export function ContainerPatchInputFromJSON(json: any): ContainerPatchInput {
    return ContainerPatchInputFromJSONTyped(json, false);
}

export function ContainerPatchInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerPatchInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'characteristics_size': !exists(json, 'characteristics_size') ? undefined : json['characteristics_size'],
        'characteristics_type': !exists(json, 'characteristics_type') ? undefined : json['characteristics_type'],
        'containerVersion': !exists(json, 'containerVersion') ? undefined : json['containerVersion'],
        'characteristics_maxPayload': !exists(json, 'characteristics_maxPayload') ? undefined : json['characteristics_maxPayload'],
        'characteristics_builtYear': !exists(json, 'characteristics_builtYear') ? undefined : json['characteristics_builtYear'],
        'volume': !exists(json, 'volume') ? undefined : json['volume'],
        'characteristics_tare': !exists(json, 'characteristics_tare') ? undefined : json['characteristics_tare'],
        'inspectionDate': !exists(json, 'inspectionDate') ? undefined : (new Date(json['inspectionDate'])),
        'cscCertNo': !exists(json, 'cscCertNo') ? undefined : json['cscCertNo'],
        'cscCertDate': !exists(json, 'cscCertDate') ? undefined : (new Date(json['cscCertDate'])),
        'characteristics_grade': !exists(json, 'characteristics_grade') ? undefined : json['characteristics_grade'],
        'cscCertLink': !exists(json, 'cscCertLink') ? undefined : json['cscCertLink'],
        'electronicsCharging': !exists(json, 'electronicsCharging') ? undefined : json['electronicsCharging'],
        'insurance': !exists(json, 'insurance') ? undefined : json['insurance'],
        'insuranceDate': !exists(json, 'insuranceDate') ? undefined : (new Date(json['insuranceDate'])),
        'cameraExt': !exists(json, 'cameraExt') ? undefined : json['cameraExt'],
        'cameraInt': !exists(json, 'cameraInt') ? undefined : json['cameraInt'],
        'floorType': !exists(json, 'floorType') ? undefined : json['floorType'],
        'doorType': !exists(json, 'doorType') ? undefined : json['doorType'],
        'depotId': !exists(json, 'depotId') ? undefined : json['depotId'],
        'lastChangedBy': !exists(json, 'lastChangedBy') ? undefined : json['lastChangedBy'],
    };
}

export function ContainerPatchInputToJSON(value?: ContainerPatchInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'characteristics_size': value.characteristics_size,
        'characteristics_type': value.characteristics_type,
        'containerVersion': value.containerVersion,
        'characteristics_maxPayload': value.characteristics_maxPayload,
        'characteristics_builtYear': value.characteristics_builtYear,
        'volume': value.volume,
        'characteristics_tare': value.characteristics_tare,
        'inspectionDate': value.inspectionDate === undefined ? undefined : (value.inspectionDate.toISOString()),
        'cscCertNo': value.cscCertNo,
        'cscCertDate': value.cscCertDate === undefined ? undefined : (value.cscCertDate.toISOString()),
        'characteristics_grade': value.characteristics_grade,
        'cscCertLink': value.cscCertLink,
        'electronicsCharging': value.electronicsCharging,
        'insurance': value.insurance,
        'insuranceDate': value.insuranceDate === undefined ? undefined : (value.insuranceDate.toISOString()),
        'cameraExt': value.cameraExt,
        'cameraInt': value.cameraInt,
        'floorType': value.floorType,
        'doorType': value.doorType,
        'depotId': value.depotId,
        'lastChangedBy': value.lastChangedBy,
    };
}


