/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentLocation
 */
export interface CurrentLocation {
    /**
     * 
     * @type {string}
     * @memberof CurrentLocation
     */
    locationId: string;
    /**
     * 
     * @type {Date}
     * @memberof CurrentLocation
     */
    validTo?: Date;
}

export function CurrentLocationFromJSON(json: any): CurrentLocation {
    return CurrentLocationFromJSONTyped(json, false);
}

export function CurrentLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationId': json['locationId'],
        'validTo': !exists(json, 'validTo') ? undefined : (new Date(json['validTo'])),
    };
}

export function CurrentLocationToJSON(value?: CurrentLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locationId': value.locationId,
        'validTo': value.validTo === undefined ? undefined : (value.validTo.toISOString()),
    };
}


