/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepotStats
 */
export interface DepotStats {
    /**
     * 
     * @type {string}
     * @memberof DepotStats
     */
    depotId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DepotStats
     */
    containersAtDepot: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DepotStats
     */
    containersArriving: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DepotStats
     */
    containersDeparting: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DepotStats
     */
    containersOverIdleLimit: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof DepotStats
     */
    containersBlocked: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DepotStats
     */
    daysIdle: number;
}

export function DepotStatsFromJSON(json: any): DepotStats {
    return DepotStatsFromJSONTyped(json, false);
}

export function DepotStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepotStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'depotId': json['depotId'],
        'containersAtDepot': json['containersAtDepot'],
        'containersArriving': json['containersArriving'],
        'containersDeparting': json['containersDeparting'],
        'containersOverIdleLimit': json['containersOverIdleLimit'],
        'containersBlocked': json['containersBlocked'],
        'daysIdle': json['daysIdle'],
    };
}

export function DepotStatsToJSON(value?: DepotStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'depotId': value.depotId,
        'containersAtDepot': value.containersAtDepot,
        'containersArriving': value.containersArriving,
        'containersDeparting': value.containersDeparting,
        'containersOverIdleLimit': value.containersOverIdleLimit,
        'containersBlocked': value.containersBlocked,
        'daysIdle': value.daysIdle,
    };
}


