/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentLeaseUpdateInput
 */
export interface EquipmentLeaseUpdateInput {
    /**
     * 
     * @type {Date}
     * @memberof EquipmentLeaseUpdateInput
     */
    stopAtActual: Date;
    /**
     * 
     * @type {string}
     * @memberof EquipmentLeaseUpdateInput
     */
    endLocationId: string;
}

export function EquipmentLeaseUpdateInputFromJSON(json: any): EquipmentLeaseUpdateInput {
    return EquipmentLeaseUpdateInputFromJSONTyped(json, false);
}

export function EquipmentLeaseUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentLeaseUpdateInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stopAtActual': (new Date(json['stopAtActual'])),
        'endLocationId': json['endLocationId'],
    };
}

export function EquipmentLeaseUpdateInputToJSON(value?: EquipmentLeaseUpdateInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stopAtActual': (value.stopAtActual.toISOString()),
        'endLocationId': value.endLocationId,
    };
}


