/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentLeaseStatusInput
 */
export interface EquipmentLeaseStatusInput {
    /**
     * orderStatus
     * @type {string}
     * @memberof EquipmentLeaseStatusInput
     */
    orderStatus: EquipmentLeaseStatusInputOrderStatusEnum;
    /**
     * contractStatus
     * @type {string}
     * @memberof EquipmentLeaseStatusInput
     */
    contractStatus: EquipmentLeaseStatusInputContractStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum EquipmentLeaseStatusInputOrderStatusEnum {
    Created = 'CREATED',
    Accepted = 'ACCEPTED',
    AelerCanceled = 'AELER-CANCELED',
    CustomerCanceled = 'CUSTOMER-CANCELED',
    CompletedFulfilled = 'COMPLETED-FULFILLED',
    CompletedFailed = 'COMPLETED-FAILED'
}/**
* @export
* @enum {string}
*/
export enum EquipmentLeaseStatusInputContractStatusEnum {
    Stl = 'STL',
    Ltl = 'LTL',
    Ael = 'AEL',
    Owl = 'OWL',
    Sal = 'SAL'
}

export function EquipmentLeaseStatusInputFromJSON(json: any): EquipmentLeaseStatusInput {
    return EquipmentLeaseStatusInputFromJSONTyped(json, false);
}

export function EquipmentLeaseStatusInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentLeaseStatusInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderStatus': json['orderStatus'],
        'contractStatus': json['contractStatus'],
    };
}

export function EquipmentLeaseStatusInputToJSON(value?: EquipmentLeaseStatusInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderStatus': value.orderStatus,
        'contractStatus': value.contractStatus,
    };
}


