/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EquipmentStatusAvailableInput
 */
export interface EquipmentStatusAvailableInput {
    /**
     * date when the previous valid status should stop
     * @type {Date}
     * @memberof EquipmentStatusAvailableInput
     */
    stopAtActual: Date;
    /**
     * confirmed depot
     * @type {string}
     * @memberof EquipmentStatusAvailableInput
     */
    depotIdActual?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentStatusAvailableInput
     */
    statusId?: string;
}

export function EquipmentStatusAvailableInputFromJSON(json: any): EquipmentStatusAvailableInput {
    return EquipmentStatusAvailableInputFromJSONTyped(json, false);
}

export function EquipmentStatusAvailableInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EquipmentStatusAvailableInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'stopAtActual': (new Date(json['stopAtActual'])),
        'depotIdActual': !exists(json, 'depotIdActual') ? undefined : json['depotIdActual'],
        'statusId': !exists(json, 'statusId') ? undefined : json['statusId'],
    };
}

export function EquipmentStatusAvailableInputToJSON(value?: EquipmentStatusAvailableInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'stopAtActual': (value.stopAtActual.toISOString()),
        'depotIdActual': value.depotIdActual,
        'statusId': value.statusId,
    };
}


