/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeojsonPoint
 */
export interface GeojsonPoint {
    /**
     * 
     * @type {string}
     * @memberof GeojsonPoint
     */
    type: GeojsonPointTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof GeojsonPoint
     */
    coordinates?: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum GeojsonPointTypeEnum {
    Point = 'Point'
}

export function GeojsonPointFromJSON(json: any): GeojsonPoint {
    return GeojsonPointFromJSONTyped(json, false);
}

export function GeojsonPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeojsonPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'coordinates': !exists(json, 'coordinates') ? undefined : json['coordinates'],
    };
}

export function GeojsonPointToJSON(value?: GeojsonPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'coordinates': value.coordinates,
    };
}


