/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model35
 */
export interface Model35 {
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof Model35
     */
    values: Array<Array<string>>;
}

export function Model35FromJSON(json: any): Model35 {
    return Model35FromJSONTyped(json, false);
}

export function Model35FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model35 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'values': json['values'],
    };
}

export function Model35ToJSON(value?: Model35 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'values': value.values,
    };
}


