/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model34
 */
export interface Model34 {
    /**
     * 
     * @type {number}
     * @memberof Model34
     */
    totalPctBlocked: number;
}

export function Model34FromJSON(json: any): Model34 {
    return Model34FromJSONTyped(json, false);
}

export function Model34FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model34 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalPctBlocked': json['totalPctBlocked'],
    };
}

export function Model34ToJSON(value?: Model34 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalPctBlocked': value.totalPctBlocked,
    };
}


