/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model30
 */
export interface Model30 {
    /**
     * 
     * @type {number}
     * @memberof Model30
     */
    totalAv: number;
}

export function Model30FromJSON(json: any): Model30 {
    return Model30FromJSONTyped(json, false);
}

export function Model30FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model30 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalAv': json['totalAv'],
    };
}

export function Model30ToJSON(value?: Model30 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalAv': value.totalAv,
    };
}


