/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model41
 */
export interface Model41 {
    /**
     * 
     * @type {string}
     * @memberof Model41
     */
    equipmentLeaseContractId: string;
    /**
     * 
     * @type {string}
     * @memberof Model41
     */
    equipmentId: string;
    /**
     * 
     * @type {string}
     * @memberof Model41
     */
    orderId: string;
    /**
     * createdAt
     * @type {Date}
     * @memberof Model41
     */
    createdAt: Date;
    /**
     * active or canceled allocation
     * @type {boolean}
     * @memberof Model41
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof Model41
     */
    comment?: string;
    /**
     * the last user who changed the object
     * @type {string}
     * @memberof Model41
     */
    lastChangedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof Model41
     */
    lastOperation?: Model41LastOperationEnum;
}

/**
* @export
* @enum {string}
*/
export enum Model41LastOperationEnum {
    D = 'D',
    C = 'C',
    U = 'U'
}

export function Model41FromJSON(json: any): Model41 {
    return Model41FromJSONTyped(json, false);
}

export function Model41FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model41 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'equipmentLeaseContractId': json['equipmentLeaseContractId'],
        'equipmentId': json['equipmentId'],
        'orderId': json['orderId'],
        'createdAt': (new Date(json['createdAt'])),
        'active': json['active'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'lastChangedByUserId': !exists(json, 'lastChangedByUserId') ? undefined : json['lastChangedByUserId'],
        'lastOperation': !exists(json, 'lastOperation') ? undefined : json['lastOperation'],
    };
}

export function Model41ToJSON(value?: Model41 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'equipmentLeaseContractId': value.equipmentLeaseContractId,
        'equipmentId': value.equipmentId,
        'orderId': value.orderId,
        'createdAt': (value.createdAt.toISOString()),
        'active': value.active,
        'comment': value.comment,
        'lastChangedByUserId': value.lastChangedByUserId,
        'lastOperation': value.lastOperation,
    };
}


