/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model22
 */
export interface Model22 {
    /**
     * 
     * @type {number}
     * @memberof Model22
     */
    orderEnds: number;
}

export function Model22FromJSON(json: any): Model22 {
    return Model22FromJSONTyped(json, false);
}

export function Model22FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model22 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderEnds': json['orderEnds'],
    };
}

export function Model22ToJSON(value?: Model22 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderEnds': value.orderEnds,
    };
}


