/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model20
 */
export interface Model20 {
    /**
     * 
     * @type {number}
     * @memberof Model20
     */
    ready: number;
}

export function Model20FromJSON(json: any): Model20 {
    return Model20FromJSONTyped(json, false);
}

export function Model20FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model20 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ready': json['ready'],
    };
}

export function Model20ToJSON(value?: Model20 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ready': value.ready,
    };
}


