/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model45
 */
export interface Model45 {
    /**
     * 
     * @type {boolean}
     * @memberof Model45
     */
    status: boolean;
}

export function Model45FromJSON(json: any): Model45 {
    return Model45FromJSONTyped(json, false);
}

export function Model45FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model45 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function Model45ToJSON(value?: Model45 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


