/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model21
 */
export interface Model21 {
    /**
     * 
     * @type {number}
     * @memberof Model21
     */
    totalOrders: number;
}

export function Model21FromJSON(json: any): Model21 {
    return Model21FromJSONTyped(json, false);
}

export function Model21FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model21 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalOrders': json['totalOrders'],
    };
}

export function Model21ToJSON(value?: Model21 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalOrders': value.totalOrders,
    };
}


