/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model27
 */
export interface Model27 {
    /**
     * 
     * @type {number}
     * @memberof Model27
     */
    pctMnr: number;
}

export function Model27FromJSON(json: any): Model27 {
    return Model27FromJSONTyped(json, false);
}

export function Model27FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model27 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pctMnr': json['pctMnr'],
    };
}

export function Model27ToJSON(value?: Model27 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pctMnr': value.pctMnr,
    };
}


