/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContainerBoardPairingProfilePatchInput,
    ContainerBoardPairingProfilePatchInputFromJSON,
    ContainerBoardPairingProfilePatchInputFromJSONTyped,
    ContainerBoardPairingProfilePatchInputToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model46
 */
export interface Model46 {
    /**
     * 
     * @type {string}
     * @memberof Model46
     */
    boardPairingProfileId: string;
    /**
     * 
     * @type {ContainerBoardPairingProfilePatchInput}
     * @memberof Model46
     */
    payload: ContainerBoardPairingProfilePatchInput;
}

export function Model46FromJSON(json: any): Model46 {
    return Model46FromJSONTyped(json, false);
}

export function Model46FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model46 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boardPairingProfileId': json['boardPairingProfileId'],
        'payload': ContainerBoardPairingProfilePatchInputFromJSON(json['payload']),
    };
}

export function Model46ToJSON(value?: Model46 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boardPairingProfileId': value.boardPairingProfileId,
        'payload': ContainerBoardPairingProfilePatchInputToJSON(value.payload),
    };
}


