/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model36
 */
export interface Model36 {
    /**
     * 
     * @type {string}
     * @memberof Model36
     */
    piecewiseTimeSeriesId: string;
    /**
     * 
     * @type {Array<Array<string>>}
     * @memberof Model36
     */
    values: Array<Array<string>>;
    /**
     * the last user who changed the object
     * @type {string}
     * @memberof Model36
     */
    lastChangedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof Model36
     */
    lastOperation?: Model36LastOperationEnum;
}

/**
* @export
* @enum {string}
*/
export enum Model36LastOperationEnum {
    D = 'D',
    C = 'C',
    U = 'U'
}

export function Model36FromJSON(json: any): Model36 {
    return Model36FromJSONTyped(json, false);
}

export function Model36FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model36 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'piecewiseTimeSeriesId': json['piecewiseTimeSeriesId'],
        'values': json['values'],
        'lastChangedByUserId': !exists(json, 'lastChangedByUserId') ? undefined : json['lastChangedByUserId'],
        'lastOperation': !exists(json, 'lastOperation') ? undefined : json['lastOperation'],
    };
}

export function Model36ToJSON(value?: Model36 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'piecewiseTimeSeriesId': value.piecewiseTimeSeriesId,
        'values': value.values,
        'lastChangedByUserId': value.lastChangedByUserId,
        'lastOperation': value.lastOperation,
    };
}


