/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicEquipmentLease
 */
export interface PublicEquipmentLease {
    /**
     * 8ddad340-6b06-4b31-9657-7c60cafed47a
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    orderId: string;
    /**
     * When the order was submitted
     * @type {Date}
     * @memberof PublicEquipmentLease
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    customerId: string;
    /**
     * Time/Date Order was placed in reality
     * @type {Date}
     * @memberof PublicEquipmentLease
     */
    timePlaced: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    pickupLocation: string;
    /**
     * planned dropoff location
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    dropoffLocation: string;
    /**
     * by default true in one way lease and AEL leases, false in LTL
     * @type {boolean}
     * @memberof PublicEquipmentLease
     */
    isDropoffLocationConfirmed: boolean;
    /**
     * Time/Date pre-agreed return date
     * @type {Date}
     * @memberof PublicEquipmentLease
     */
    returnDate: Date;
    /**
     * Time/Date the order begins
     * @type {Date}
     * @memberof PublicEquipmentLease
     */
    executionDate: Date;
    /**
     * Number of units requested
     * @type {number}
     * @memberof PublicEquipmentLease
     */
    units: number;
    /**
     * 
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    dropoffLocationActual?: string;
    /**
     * Customers own booking number
     * @type {string}
     * @memberof PublicEquipmentLease
     */
    customersBookingNumber?: string;
}

export function PublicEquipmentLeaseFromJSON(json: any): PublicEquipmentLease {
    return PublicEquipmentLeaseFromJSONTyped(json, false);
}

export function PublicEquipmentLeaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicEquipmentLease {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'createdAt': (new Date(json['createdAt'])),
        'customerId': json['customerId'],
        'timePlaced': (new Date(json['timePlaced'])),
        'pickupLocation': json['pickupLocation'],
        'dropoffLocation': json['dropoffLocation'],
        'isDropoffLocationConfirmed': json['isDropoffLocationConfirmed'],
        'returnDate': (new Date(json['returnDate'])),
        'executionDate': (new Date(json['executionDate'])),
        'units': json['units'],
        'dropoffLocationActual': !exists(json, 'dropoffLocationActual') ? undefined : json['dropoffLocationActual'],
        'customersBookingNumber': !exists(json, 'customersBookingNumber') ? undefined : json['customersBookingNumber'],
    };
}

export function PublicEquipmentLeaseToJSON(value?: PublicEquipmentLease | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'createdAt': (value.createdAt.toISOString()),
        'customerId': value.customerId,
        'timePlaced': (value.timePlaced.toISOString()),
        'pickupLocation': value.pickupLocation,
        'dropoffLocation': value.dropoffLocation,
        'isDropoffLocationConfirmed': value.isDropoffLocationConfirmed,
        'returnDate': (value.returnDate.toISOString()),
        'executionDate': (value.executionDate.toISOString()),
        'units': value.units,
        'dropoffLocationActual': value.dropoffLocationActual,
        'customersBookingNumber': value.customersBookingNumber,
    };
}


