/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentStatus
 */
export interface ShipmentStatus {
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatus
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatus
     */
    requesterId: string;
    /**
     * the last user who changed the object
     * @type {string}
     * @memberof ShipmentStatus
     */
    lastChangedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatus
     */
    lastOperation?: ShipmentStatusLastOperationEnum;
    /**
     * 
     * @type {string}
     * @memberof ShipmentStatus
     */
    shipmentId: string;
    /**
     * When the move status was submitted
     * @type {Date}
     * @memberof ShipmentStatus
     */
    createdAt: Date;
    /**
     * shipment status during a shipment
     * @type {string}
     * @memberof ShipmentStatus
     */
    status: ShipmentStatusStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ShipmentStatus
     */
    isCurrent: boolean;
}

/**
* @export
* @enum {string}
*/
export enum ShipmentStatusLastOperationEnum {
    D = 'D',
    C = 'C',
    U = 'U'
}/**
* @export
* @enum {string}
*/
export enum ShipmentStatusStatusEnum {
    Created = 'CREATED',
    Open = 'OPEN',
    Closed = 'CLOSED',
    Intransit = 'INTRANSIT',
    Arrived = 'ARRIVED',
    Failed = 'FAILED'
}

export function ShipmentStatusFromJSON(json: any): ShipmentStatus {
    return ShipmentStatusFromJSONTyped(json, false);
}

export function ShipmentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerId': json['ownerId'],
        'requesterId': json['requesterId'],
        'lastChangedByUserId': !exists(json, 'lastChangedByUserId') ? undefined : json['lastChangedByUserId'],
        'lastOperation': !exists(json, 'lastOperation') ? undefined : json['lastOperation'],
        'shipmentId': json['shipmentId'],
        'createdAt': (new Date(json['createdAt'])),
        'status': json['status'],
        'isCurrent': json['isCurrent'],
    };
}

export function ShipmentStatusToJSON(value?: ShipmentStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ownerId': value.ownerId,
        'requesterId': value.requesterId,
        'lastChangedByUserId': value.lastChangedByUserId,
        'lastOperation': value.lastOperation,
        'shipmentId': value.shipmentId,
        'createdAt': (value.createdAt.toISOString()),
        'status': value.status,
        'isCurrent': value.isCurrent,
    };
}


