/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentCargoInput
 */
export interface ShipmentCargoInput {
    /**
     * 
     * @type {string}
     * @memberof ShipmentCargoInput
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentCargoInput
     */
    quantity: string;
}

export function ShipmentCargoInputFromJSON(json: any): ShipmentCargoInput {
    return ShipmentCargoInputFromJSONTyped(json, false);
}

export function ShipmentCargoInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentCargoInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': json['description'],
        'quantity': json['quantity'],
    };
}

export function ShipmentCargoInputToJSON(value?: ShipmentCargoInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'quantity': value.quantity,
    };
}


