/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentStatusInput
 */
export interface ShipmentStatusInput {
    /**
     * shipment status during a shipment
     * @type {string}
     * @memberof ShipmentStatusInput
     */
    status: ShipmentStatusInputStatusEnum;
}

/**
* @export
* @enum {string}
*/
export enum ShipmentStatusInputStatusEnum {
    Created = 'CREATED',
    Open = 'OPEN',
    Closed = 'CLOSED',
    Intransit = 'INTRANSIT',
    Arrived = 'ARRIVED',
    Failed = 'FAILED'
}

export function ShipmentStatusInputFromJSON(json: any): ShipmentStatusInput {
    return ShipmentStatusInputFromJSONTyped(json, false);
}

export function ShipmentStatusInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentStatusInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ShipmentStatusInputToJSON(value?: ShipmentStatusInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}


