/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShipmentTransport
 */
export interface ShipmentTransport {
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    ownerId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    requesterId: string;
    /**
     * the last user who changed the object
     * @type {string}
     * @memberof ShipmentTransport
     */
    lastChangedByUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    lastOperation?: ShipmentTransportLastOperationEnum;
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    shipmentTransportId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    shipmentId: string;
    /**
     * 
     * @type {string}
     * @memberof ShipmentTransport
     */
    transportResponsible: string;
}

/**
* @export
* @enum {string}
*/
export enum ShipmentTransportLastOperationEnum {
    D = 'D',
    C = 'C',
    U = 'U'
}

export function ShipmentTransportFromJSON(json: any): ShipmentTransport {
    return ShipmentTransportFromJSONTyped(json, false);
}

export function ShipmentTransportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentTransport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerId': json['ownerId'],
        'requesterId': json['requesterId'],
        'lastChangedByUserId': !exists(json, 'lastChangedByUserId') ? undefined : json['lastChangedByUserId'],
        'lastOperation': !exists(json, 'lastOperation') ? undefined : json['lastOperation'],
        'shipmentTransportId': json['shipmentTransportId'],
        'shipmentId': json['shipmentId'],
        'transportResponsible': json['transportResponsible'],
    };
}

export function ShipmentTransportToJSON(value?: ShipmentTransport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ownerId': value.ownerId,
        'requesterId': value.requesterId,
        'lastChangedByUserId': value.lastChangedByUserId,
        'lastOperation': value.lastOperation,
        'shipmentTransportId': value.shipmentTransportId,
        'shipmentId': value.shipmentId,
        'transportResponsible': value.transportResponsible,
    };
}


