/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Transport,
    TransportFromJSON,
    TransportFromJSONTyped,
    TransportToJSON,
    TransportRef,
    TransportRefFromJSON,
    TransportRefFromJSONTyped,
    TransportRefToJSON,
} from './';

/**
 * 
 * @export
 * @interface ShipmentTransportInput
 */
export interface ShipmentTransportInput {
    /**
     * 
     * @type {Transport}
     * @memberof ShipmentTransportInput
     */
    transport: Transport;
    /**
     * 
     * @type {TransportRef}
     * @memberof ShipmentTransportInput
     */
    transportRef?: TransportRef;
}

export function ShipmentTransportInputFromJSON(json: any): ShipmentTransportInput {
    return ShipmentTransportInputFromJSONTyped(json, false);
}

export function ShipmentTransportInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShipmentTransportInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transport': TransportFromJSON(json['transport']),
        'transportRef': !exists(json, 'transportRef') ? undefined : TransportRefFromJSON(json['transportRef']),
    };
}

export function ShipmentTransportInputToJSON(value?: ShipmentTransportInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transport': TransportToJSON(value.transport),
        'transportRef': TransportRefToJSON(value.transportRef),
    };
}


