/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Warnings
 */
export interface Warnings {
    /**
     * 
     * @type {boolean}
     * @memberof Warnings
     */
    hasStartBeforeStop?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Warnings
     */
    hasMissingStopActual?: boolean;
}

export function WarningsFromJSON(json: any): Warnings {
    return WarningsFromJSONTyped(json, false);
}

export function WarningsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Warnings {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasStartBeforeStop': !exists(json, 'hasStartBeforeStop') ? undefined : json['hasStartBeforeStop'],
        'hasMissingStopActual': !exists(json, 'hasMissingStopActual') ? undefined : json['hasMissingStopActual'],
    };
}

export function WarningsToJSON(value?: Warnings | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasStartBeforeStop': value.hasStartBeforeStop,
        'hasMissingStopActual': value.hasMissingStopActual,
    };
}


