/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatteryMeasurement
 */
export interface BatteryMeasurement {
    /**
     * from 0 to 100
     * @type {number}
     * @memberof BatteryMeasurement
     */
    batteryLevel: number;
}

export function BatteryMeasurementFromJSON(json: any): BatteryMeasurement {
    return BatteryMeasurementFromJSONTyped(json, false);
}

export function BatteryMeasurementFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatteryMeasurement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'batteryLevel': json['batteryLevel'],
    };
}

export function BatteryMeasurementToJSON(value?: BatteryMeasurement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'batteryLevel': value.batteryLevel,
    };
}


