/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DepotCity,
    DepotCityFromJSON,
    DepotCityFromJSONTyped,
    DepotCityToJSON,
    DepotCountry,
    DepotCountryFromJSON,
    DepotCountryFromJSONTyped,
    DepotCountryToJSON,
} from './';

/**
 * 
 * @export
 * @interface DepotAddress
 */
export interface DepotAddress {
    /**
     * 
     * @type {string}
     * @memberof DepotAddress
     */
    region: string;
    /**
     * 
     * @type {DepotCountry}
     * @memberof DepotAddress
     */
    country: DepotCountry;
    /**
     * 
     * @type {DepotCity}
     * @memberof DepotAddress
     */
    city: DepotCity;
    /**
     * 
     * @type {string}
     * @memberof DepotAddress
     */
    name?: string;
}

export function DepotAddressFromJSON(json: any): DepotAddress {
    return DepotAddressFromJSONTyped(json, false);
}

export function DepotAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepotAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'region': json['region'],
        'country': DepotCountryFromJSON(json['country']),
        'city': DepotCityFromJSON(json['city']),
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function DepotAddressToJSON(value?: DepotAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'region': value.region,
        'country': DepotCountryToJSON(value.country),
        'city': DepotCityToJSON(value.city),
        'name': value.name,
    };
}


