/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepotCity
 */
export interface DepotCity {
    /**
     * 
     * @type {string}
     * @memberof DepotCity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DepotCity
     */
    identifiers_iso5?: string;
}

export function DepotCityFromJSON(json: any): DepotCity {
    return DepotCityFromJSONTyped(json, false);
}

export function DepotCityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepotCity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'identifiers_iso5': !exists(json, 'identifiers_iso5') ? undefined : json['identifiers_iso5'],
    };
}

export function DepotCityToJSON(value?: DepotCity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'identifiers_iso5': value.identifiers_iso5,
    };
}


