/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * DepotInputOptional
 * @export
 * @interface DepotInputOptional
 */
export interface DepotInputOptional {
    /**
     * location Id
     * @type {string}
     * @memberof DepotInputOptional
     */
    locationId?: string;
}

export function DepotInputOptionalFromJSON(json: any): DepotInputOptional {
    return DepotInputOptionalFromJSONTyped(json, false);
}

export function DepotInputOptionalFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepotInputOptional {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'locationId': !exists(json, 'locationId') ? undefined : json['locationId'],
    };
}

export function DepotInputOptionalToJSON(value?: DepotInputOptional | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'locationId': value.locationId,
    };
}


