/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CityInput,
    CityInputFromJSON,
    CityInputFromJSONTyped,
    CityInputToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model11
 */
export interface Model11 {
    /**
     * name
     * @type {string}
     * @memberof Model11
     */
    name: string;
    /**
     * 
     * @type {CityInput}
     * @memberof Model11
     */
    optional?: CityInput;
}

export function Model11FromJSON(json: any): Model11 {
    return Model11FromJSONTyped(json, false);
}

export function Model11FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model11 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'optional': !exists(json, 'optional') ? undefined : CityInputFromJSON(json['optional']),
    };
}

export function Model11ToJSON(value?: Model11 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'optional': CityInputToJSON(value.optional),
    };
}


