/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FacilityInputOptional,
    FacilityInputOptionalFromJSON,
    FacilityInputOptionalFromJSONTyped,
    FacilityInputOptionalToJSON,
} from './';

/**
 * 
 * @export
 * @interface PatchFacilityInput
 */
export interface PatchFacilityInput {
    /**
     * Facility name
     * @type {string}
     * @memberof PatchFacilityInput
     */
    name?: string;
    /**
     * 4 letter code for company/name
     * @type {string}
     * @memberof PatchFacilityInput
     */
    code?: string;
    /**
     * address id
     * @type {string}
     * @memberof PatchFacilityInput
     */
    addressId?: string;
    /**
     * partnership types
     * @type {Array<string>}
     * @memberof PatchFacilityInput
     */
    partnershipTypes?: Array<PatchFacilityInputPartnershipTypesEnum>;
    /**
     * types of facilities
     * @type {string}
     * @memberof PatchFacilityInput
     */
    type?: PatchFacilityInputTypeEnum;
    /**
     * 
     * @type {FacilityInputOptional}
     * @memberof PatchFacilityInput
     */
    optional?: FacilityInputOptional;
}

/**
* @export
* @enum {string}
*/
export enum PatchFacilityInputPartnershipTypesEnum {
    Storage = 'Storage',
    MnR = 'MnR',
    Haulage = 'Haulage'
}/**
* @export
* @enum {string}
*/
export enum PatchFacilityInputTypeEnum {
    Bocr = 'BOCR',
    Culo = 'CULO',
    Cofs = 'COFS',
    Coya = 'COYA',
    Depo = 'DEPO',
    Inte = 'INTE',
    Pote = 'POTE',
    Pbst = 'PBST'
}

export function PatchFacilityInputFromJSON(json: any): PatchFacilityInput {
    return PatchFacilityInputFromJSONTyped(json, false);
}

export function PatchFacilityInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchFacilityInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'addressId': !exists(json, 'addressId') ? undefined : json['addressId'],
        'partnershipTypes': !exists(json, 'partnershipTypes') ? undefined : json['partnershipTypes'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'optional': !exists(json, 'optional') ? undefined : FacilityInputOptionalFromJSON(json['optional']),
    };
}

export function PatchFacilityInputToJSON(value?: PatchFacilityInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'code': value.code,
        'addressId': value.addressId,
        'partnershipTypes': value.partnershipTypes,
        'type': value.type,
        'optional': FacilityInputOptionalToJSON(value.optional),
    };
}


