/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model7
 */
export interface Model7 {
    /**
     * the user
     * @type {string}
     * @memberof Model7
     */
    userId: string;
    /**
     * the alert
     * @type {string}
     * @memberof Model7
     */
    alertStateId: string;
    /**
     * 
     * @type {Date}
     * @memberof Model7
     */
    readAt?: Date | null;
    /**
     * is it snoozed
     * @type {boolean}
     * @memberof Model7
     */
    isSnoozed?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Model7
     */
    snoozeUntil?: Date;
}

export function Model7FromJSON(json: any): Model7 {
    return Model7FromJSONTyped(json, false);
}

export function Model7FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model7 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'alertStateId': json['alertStateId'],
        'readAt': !exists(json, 'readAt') ? undefined : (json['readAt'] === null ? null : new Date(json['readAt'])),
        'isSnoozed': !exists(json, 'isSnoozed') ? undefined : json['isSnoozed'],
        'snoozeUntil': !exists(json, 'snoozeUntil') ? undefined : (new Date(json['snoozeUntil'])),
    };
}

export function Model7ToJSON(value?: Model7 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'alertStateId': value.alertStateId,
        'readAt': value.readAt === undefined ? undefined : (value.readAt === null ? null : value.readAt.toISOString()),
        'isSnoozed': value.isSnoozed,
        'snoozeUntil': value.snoozeUntil === undefined ? undefined : (value.snoozeUntil.toISOString()),
    };
}


