/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingNotificationsInput
 */
export interface PendingNotificationsInput {
    /**
     * 
     * @type {string}
     * @memberof PendingNotificationsInput
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof PendingNotificationsInput
     */
    shouldDismiss: boolean;
}

export function PendingNotificationsInputFromJSON(json: any): PendingNotificationsInput {
    return PendingNotificationsInputFromJSONTyped(json, false);
}

export function PendingNotificationsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingNotificationsInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'shouldDismiss': json['shouldDismiss'],
    };
}

export function PendingNotificationsInputToJSON(value?: PendingNotificationsInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'shouldDismiss': value.shouldDismiss,
    };
}


