/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Failure,
    FailureFromJSON,
    FailureToJSON,
    Model4,
    Model4FromJSON,
    Model4ToJSON,
} from '../models';

export interface GetEvalstepspiecewisetimeseriesRequest {
    date: string;
    startDate: string;
    timeSeriesId: string;
}

/**
 * 
 */
export class EvalStepsPiecewiseTimeseriesApi extends runtime.BaseAPI {

    /**
     * Eval Steps Piecewise Timeseries
     */
    async getEvalstepspiecewisetimeseriesRaw(requestParameters: GetEvalstepspiecewisetimeseriesRequest): Promise<runtime.ApiResponse<Model4>> {
        if (requestParameters.date === null || requestParameters.date === undefined) {
            throw new runtime.RequiredError('date','Required parameter requestParameters.date was null or undefined when calling getEvalstepspiecewisetimeseries.');
        }

        if (requestParameters.startDate === null || requestParameters.startDate === undefined) {
            throw new runtime.RequiredError('startDate','Required parameter requestParameters.startDate was null or undefined when calling getEvalstepspiecewisetimeseries.');
        }

        if (requestParameters.timeSeriesId === null || requestParameters.timeSeriesId === undefined) {
            throw new runtime.RequiredError('timeSeriesId','Required parameter requestParameters.timeSeriesId was null or undefined when calling getEvalstepspiecewisetimeseries.');
        }

        const queryParameters: any = {};

        if (requestParameters.date !== undefined) {
            queryParameters['date'] = requestParameters.date;
        }

        if (requestParameters.startDate !== undefined) {
            queryParameters['startDate'] = requestParameters.startDate;
        }

        if (requestParameters.timeSeriesId !== undefined) {
            queryParameters['timeSeriesId'] = requestParameters.timeSeriesId;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // jwt authentication
        }

        const response = await this.request({
            path: `/evalStepsPiecewiseTimeseries`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => Model4FromJSON(jsonValue));
    }

    /**
     * Eval Steps Piecewise Timeseries
     */
    async getEvalstepspiecewisetimeseries(requestParameters: GetEvalstepspiecewisetimeseriesRequest): Promise<Model4> {
        const response = await this.getEvalstepspiecewisetimeseriesRaw(requestParameters);
        return await response.value();
    }

}
