/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ExchangeLocation,
    ExchangeLocationFromJSON,
    ExchangeLocationToJSON,
    ExchangeLocationInput,
    ExchangeLocationInputFromJSON,
    ExchangeLocationInputToJSON,
    Failure,
    FailureFromJSON,
    FailureToJSON,
} from '../models';

export interface GetLocationsRequest {
    nameStartsWith?: string;
}

export interface PostLocationsRequest {
    body?: ExchangeLocationInput;
}

/**
 * 
 */
export class LocationsApi extends runtime.BaseAPI {

    /**
     * get location
     */
    async getLocationsRaw(requestParameters: GetLocationsRequest): Promise<runtime.ApiResponse<Array<ExchangeLocation>>> {
        const queryParameters: any = {};

        if (requestParameters.nameStartsWith !== undefined) {
            queryParameters['nameStartsWith'] = requestParameters.nameStartsWith;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // jwt authentication
        }

        const response = await this.request({
            path: `/locations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExchangeLocationFromJSON));
    }

    /**
     * get location
     */
    async getLocations(requestParameters: GetLocationsRequest): Promise<Array<ExchangeLocation>> {
        const response = await this.getLocationsRaw(requestParameters);
        return await response.value();
    }

    /**
     * FIXME
     */
    async postLocationsRaw(requestParameters: PostLocationsRequest): Promise<runtime.ApiResponse<ExchangeLocation>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // jwt authentication
        }

        const response = await this.request({
            path: `/locations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExchangeLocationInputToJSON(requestParameters.body),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => ExchangeLocationFromJSON(jsonValue));
    }

    /**
     * FIXME
     */
    async postLocations(requestParameters: PostLocationsRequest): Promise<ExchangeLocation> {
        const response = await this.postLocationsRaw(requestParameters);
        return await response.value();
    }

}
