/* tslint:disable */
/* eslint-disable */
/**
 * Aeler demo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Values,
    ValuesFromJSON,
    ValuesFromJSONTyped,
    ValuesToJSON,
} from './';

/**
 * 
 * @export
 * @interface Model2
 */
export interface Model2 {
    /**
     * 
     * @type {string}
     * @memberof Model2
     */
    boardId: string;
    /**
     * 
     * @type {Values}
     * @memberof Model2
     */
    values: Values;
}

export function Model2FromJSON(json: any): Model2 {
    return Model2FromJSONTyped(json, false);
}

export function Model2FromJSONTyped(json: any, ignoreDiscriminator: boolean): Model2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'boardId': json['boardId'],
        'values': ValuesFromJSON(json['values']),
    };
}

export function Model2ToJSON(value?: Model2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'boardId': value.boardId,
        'values': ValuesToJSON(value.values),
    };
}


